### ISSUE TITLE
[Cmake] cmake example for Plugins wanted

### ISSUE THREAD

**Issue by qPexLegendary** [LiteLDev/PluginTemplate#2]
I know this project created for VisualStudio, but for some VS it is difficult to use. Overloaded interface, code autocompletion works crookedly, very big project weight(starting from 1GB). Many who love software from JetBrains. Me too. I tried to remake the project for СLion, but nothing came of it. Is there any ready-made solution or suggestion how this can be done?

UPD: I mean about plugin development.

**Comment by RimuruChan** [comment]
eb21261d3db27040d1e6071485d20ea92c831789

**Comment by RimuruChan** [comment]
CMakeList.txt is used for CLion to collect the symbol information. It's difficult to support compilation.
Please use Visual Studio to Initialize the project and build with it too.
